# Flight Advisor Docker Compose - Updated October 6, 2025
version: '3.8'
services:
  flight-advisor:
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flightdb
      - SPRING_DATASOURCE_USERNAME=flight
      - SPRING_DATASOURCE_PASSWORD=change_me
      - SERVER_PORT=8090
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/flight/service/api/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: flightdb
      POSTGRES_USER: flight
      POSTGRES_PASSWORD: change_me
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flight -d flightdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
