name: CI - Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw
        
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
            
      - name: Clean workspace and remove database files
        run: |
          ./mvnw -B clean
          rm -rf db/*.db db/*.trace.db logs/* || true
          
      - name: Compile project
        run: ./mvnw -B compile test-compile
        
      - name: List test files
        run: find src/test -name "*.java" -type f
        
      - name: Run unit tests with timeout and proper configuration
        run: |
          timeout 600 ./mvnw -B test \
            -Dspring.profiles.active=test \
            -Dmaven.test.failure.ignore=false \
            -DforkCount=1 \
            -DreuseForks=false \
            -Djava.awt.headless=true \
            -Dspring.main.banner-mode=off
        env:
          SPRING_PROFILES_ACTIVE: test
          MAVEN_OPTS: "-Xmx512m -Djava.awt.headless=true"
          
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
          retention-days: 30
          
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            target/surefire-reports/
            logs/
          retention-days: 30
