name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw
        
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
            
      - name: Clean previous builds
        run: ./mvnw -B clean
        
      - name: Compile application
        run: ./mvnw -B compile
        
      - name: Run tests with explicit profile
        run: ./mvnw -B test -Dspring.profiles.active=test -Dmaven.test.failure.ignore=false
        env:
          SPRING_PROFILES_ACTIVE: test
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
